# This is a homemade workflow, no references necessary here
---
on: [issue_comment, workflow_dispatch]
name: Autoreply to issue comments
jobs:
  build:
    name: Issue auto-commenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sending REST API request
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          COMMENTER: ${{ github.event.comment.user.login }}
        run: .github/workflows/autocomment.sh
