# https://github.com/Cyb3r-Jak3/html5validator-action#keep-up-to-date-with-github-dependabot
---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
