# https://github.com/marketplace/actions/web-deploy-anything
---
on:
  push:
    branches:
      - master

name: Test Publishing via SSH  # DOES NOT DEPLOY CHANGES!
jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/pr-merge.yml
    # Providing nothing to dry-run, since this is the real publish!
    secrets: inherit
